Create API
zarhus/listmonk-api pull request #1
Opened 2024-07-22 11:53 UTC by PLangowski

2024-08-08 15:51 UTC, artur-rs commented on README.md
> +administrator account.
@PLangowski are there any problems with user access management in listmonk? We shouldn't use single account creds used by multiple employees

2024-08-19 06:07 UTC, PLangowski commented on README.md
> +administrator account.
I haven't tested using other accounts.

2024-08-19 06:16 UTC, PLangowski commented on README.md
> +administrator account.
It seems that multiple accounts are not yet supported in listmonk https://github.com/knadh/listmonk/issues/543

2024-09-02 08:32 UTC, dancios commented on api/client.go
> +			inc_campaign = camp
I see camelCase vs _ in code:)

2024-09-02 08:35 UTC, dancios commented on api/client.go
> +	MailingListIDs map[string]uint
What if few instances woud work try access map

2024-09-12 10:28 UTC, dancios requested changes
i probably forgot to click "review chages" after writing comments :D

2024-10-22 16:00 UTC, artur-rs approved these changes

2024-10-24 10:13 UTC, merged